// OTOMATİK ÜRETİLDİ — "AI_LAB_Kitap_Listesi_FINAL.xlsx" (150 kitap, 8 kategori) + kapaklar
// (mevcut küratörlü kapaklar korunur; yeni kitaplar Open Library / Google Books).
// Kapağı bulunamayanlar null — admin panelinden kapak URL'i elle eklenebilir.
// 2026-07-03: 11 kitap listeden çıkarıldı (Excel no: 33, 39, 40, 44, 75-81); toplam 139.
// (No 23 "Sağlık Hizmetlerinde Yapay Zekâ" aktif ödünçte olduğu için listede tutuldu.)

export interface SeedBook {
  id: string;
  title: string;
  author: string;
  category: string;
  description: string;
  coverImageUrl: string | null;
  totalCopies: number;
}

export const SEED_BOOKS: SeedBook[] = [
  {
    id: "book_xl_001",
    title: "50 Soruda Yapay Zekâ",
    author: "Cem Say",
    category: "Giriş",
    description: "Türk yazar, orijinal Türkçe popüler bilim · Bilim ve Gelecek Kitaplığı · 2018",
    coverImageUrl: "https://covers.openlibrary.org/b/id/10838611-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_002",
    title: "Yaşam 3.0: Yapay Zekâ Çağında İnsan Olmak",
    author: "Max Tegmark",
    category: "Giriş",
    description: "AI ve gelecek üzerine en popüler giriş · Pegasus · 2019",
    coverImageUrl: "https://covers.openlibrary.org/b/id/10239283-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_003",
    title: "Master Algoritma",
    author: "Pedro Domingos",
    category: "Giriş",
    description: "Baskısı tükenmiş, Nadir Kitap'tan · Paloma Yayınları · 2017",
    coverImageUrl: "https://i.dr.com.tr/cache/500x400-0/originals/0001689525001-1.jpg",
    totalCopies: 1,
  },
  {
    id: "book_xl_004",
    title: "Makine Öğrenmesi",
    author: "Ethem Alpaydın",
    category: "Giriş",
    description: "MIT Press Essential Knowledge TR baskısı · Boğaziçi Üniversitesi Yayınevi · 2017",
    coverImageUrl: "https://s3.cloud.ngn.com.tr/kitantik/images/2024-01-27/1br9qfwlrv7899c1cl1.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_005",
    title: "Veri Bilimi",
    author: "John D. Kelleher & Brendan Tierney",
    category: "Giriş",
    description: "MIT Press Essential Knowledge TR; veri biliminin felsefesi · Tellekt · 2020",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12269965-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_006",
    title: "Üretici Yapay Zeka: Temel Bilgiler",
    author: "Henrik Kniberg",
    category: "Giriş",
    description: "Viral video kitap; el çizimli, pratik GenAI rehberi · Leanpub (dijital) · 2024",
    coverImageUrl: "https://m.media-amazon.com/images/P/B0DTK6ZVWX.01._SCLZZZZZZZ_.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_007",
    title: "Veri Bilimi ve Analitiği (Giriş)",
    author: "Yüksel Yurtay (Dr.)",
    category: "Giriş",
    description: "Türk yazar, iş zekası ve stratejik karar alma · Ekin Kitabevi · 2024",
    coverImageUrl: "https://www.ekinkitap.com/u/ekinyayinevi/img/c/v/e/veri-bilimi-ve-analitigi-girisb7c55870627963f98cee24c8b0178ef2.png",
    totalCopies: 2,
  },
  {
    id: "book_xl_008",
    title: "Why Machines Learn: The Elegant Math Behind Modern AI",
    author: "Anil Ananthaswamy",
    category: "Giriş",
    description: "Modern AI'nın ardındaki matematiği hikâyeleştiren popüler bilim · Dutton · 2024",
    coverImageUrl: "https://covers.openlibrary.org/b/id/15139089-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_076",
    title: "Introduction to Artificial Intelligence and Machine Learning",
    author: "R. Kelly Rainer",
    category: "Giriş",
    description: "İş odaklı, teknik altyapı gerektirmeyen AI/ML girişi; model geliştirme, dağıtım ve bakımı · Wiley · 2025",
    coverImageUrl: "https://m.media-amazon.com/images/P/1394344716.01.L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_009",
    title: "Yapay Öğrenme",
    author: "Ethem Alpaydın",
    category: "Uygulama",
    description: "Türk yazar, ML referans · Boğaziçi Üniversitesi Yayınevi · 2013",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12255229-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_010",
    title: "Tensorflow ile Derin Öğrenme",
    author: "Ümit Tunç",
    category: "Uygulama",
    description: "Türk yazar, Python + TF + Keras + CNN + GAN · Kodlab Yayın Dağıtım · 2022",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12213684-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_011",
    title: "Python: Veri Analizi, Görselleştirme ve Yapay Zekâ",
    author: "Ayhan Bozkurt",
    category: "Uygulama",
    description: "NumPy, Pandas, Scikit-learn, PyTorch — tek kaynak · Kitapyurdu Doğrudan Yayıncılık · 2024",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:11832762/wi:800/wh:91b4f2d9c",
    totalCopies: 2,
  },
  {
    id: "book_xl_012",
    title: "Yapay Zeka: Derin Öğrenme, Stratejili Oyunlar, NLP",
    author: "Vasif Nabiyev",
    category: "Uygulama",
    description: "Türk akademisyen, 6. baskı · Seçkin Yayıncılık · 2024",
    coverImageUrl: "https://image01.idefix.com/resize/500/0/product/603109/yapay-zeka-prof-dr-vasif-nabiyev-seckin-yayincilik-64edcdb7297c8.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_013",
    title: "Yapay Zekâyı Kodlamak",
    author: "Özlem Sebetci Ural",
    category: "Uygulama",
    description: "Python ile denetimli/denetimsiz/pekiştirmeli öğrenme · Seçkin Yayıncılık · 2023",
    coverImageUrl: "https://cdn.seckin.com.tr/getimage/book/956928793_400_wm.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_014",
    title: "Uygulamalar ile Python ve Yapay Zekâ",
    author: "Emrah Aydemir",
    category: "Uygulama",
    description: "Türk akademisyen, 100+ örnek uygulama · Akademisyen Kitabevi · 2021",
    coverImageUrl: "https://i.dr.com.tr/cache/500x400-0/originals/0001946163001-1.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_015",
    title: "Yapay Zeka Mühendisliği Seti (4 Kitap)",
    author: "Kolektif",
    category: "Uygulama",
    description: "AI + Derin Öğrenme + MATLAB + Python 3 · Kodlab Yayın Dağıtım · 2019",
    coverImageUrl: "https://i.dr.com.tr/cache/500x400-0/originals/0001833994001-1.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_016",
    title: "Veri Bilimi İçin Python",
    author: "Bülent Çobanoğlu",
    category: "Uygulama",
    description: "Türk yazar, 512 sayfa kapsamlı · Kodlab Yayın Dağıtım · 2021",
    coverImageUrl: "https://www.kodlab.com/2163-thickbox_default/veri-bilimi-icin-python.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_017",
    title: "Veri Bilimi İçin Python (Çözümlü Örnekler)",
    author: "Burak Özkan & Yalçın Özkan",
    category: "Uygulama",
    description: "Türk yazar, NumPy/Pandas/scikit ile uygulamalar · Papatya Bilim Yayınevi · 2024",
    coverImageUrl: "https://i.dr.com.tr/cache/500x400-0/originals/0002018235001-1.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_018",
    title: "Hands-On Machine Learning with Scikit-Learn and PyTorch",
    author: "Aurélien Géron",
    category: "Uygulama",
    description: "Géron'un 2025 yeni baskısı: PyTorch, Hugging Face, LLM fine-tuning, RL ajanları · O'Reilly · 2025",
    coverImageUrl: "https://covers.openlibrary.org/b/id/15138297-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_019",
    title: "Deep Learning with Python (3. baskı)",
    author: "François Chollet & Matthew Watson",
    category: "Uygulama",
    description: "Keras kurucusundan 2025 baskısı: Keras 3, PyTorch, JAX, kendi GPT'ni ve difüzyon modelini kur · Manning · 2025",
    coverImageUrl: "https://covers.openlibrary.org/b/id/8507718-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_020",
    title: "Build a Large Language Model (from Scratch)",
    author: "Sebastian Raschka",
    category: "Uygulama",
    description: "LLM'i PyTorch ile sıfırdan kodlama · Manning · 2024",
    coverImageUrl: "https://covers.openlibrary.org/b/id/15225524-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_021",
    title: "Yorumlanabilir ve Açıklanabilir Yapay Zekâ",
    author: "Kolektif (Şeref Sağıroğlu vd.)",
    category: "Uygulama",
    description: "Türk akademisyenler, XAI üzerine seri 4. cilt · Nobel Akademik Yayıncılık · 2024",
    coverImageUrl: "https://cdn.seckin.com.tr/getimage/book/877116445_400_wm.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_023",
    title: "Designing Machine Learning Systems",
    author: "Chip Huyen",
    category: "Uygulama",
    description: "Üretim ortamında ML sistem tasarımı, MLOps standardı · O'Reilly · 2022",
    coverImageUrl: "https://covers.openlibrary.org/b/id/13314480-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_024",
    title: "Generative Deep Learning (2. baskı)",
    author: "David Foster",
    category: "Uygulama",
    description: "VAE, GAN, difüzyon ve transformer mimarileri ile üretici modeller · O'Reilly · 2023",
    coverImageUrl: "https://covers.openlibrary.org/b/id/13272037-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_025",
    title: "Generative AI Design Patterns",
    author: "Valliappa Lakshmanan & Hannes Hapke",
    category: "Uygulama",
    description: "GenAI ajanları ve uygulamaları için 32 tasarım deseni: RAG, akıl yürütme, korkuluklar · O'Reilly · 2025",
    coverImageUrl: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1759527958i/242375746.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_026",
    title: "Python for Data Analysis (3. baskı)",
    author: "Wes McKinney",
    category: "Uygulama",
    description: "Pandas'ın yaratıcısından veri analizi temel referansı · O'Reilly · 2022",
    coverImageUrl: "https://covers.openlibrary.org/b/id/7548132-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_027",
    title: "Practical Statistics for Data Scientists (2. baskı)",
    author: "Peter Bruce, Andrew Bruce & Peter Gedeck",
    category: "Uygulama",
    description: "Veri bilimi için uygulamalı istatistik, Python + R örnekli · O'Reilly · 2020",
    coverImageUrl: "https://covers.openlibrary.org/b/id/8512070-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_028",
    title: "Artificial Intelligence: A Modern Approach (4. baskı)",
    author: "Stuart Russell & Peter Norvig",
    category: "Uygulama",
    description: "Dünyada en yaygın okutulan AI ders kitabı, kapsamlı akademik referans · Pearson · 2020",
    coverImageUrl: "https://covers.openlibrary.org/b/isbn/9780134610993-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_029",
    title: "Deep Learning",
    author: "Ian Goodfellow, Yoshua Bengio & Aaron Courville",
    category: "Uygulama",
    description: "Derin öğrenmenin teorik temel referansı, akademik standart · MIT Press · 2016",
    coverImageUrl: "https://covers.openlibrary.org/b/id/8086288-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_030",
    title: "Reinforcement Learning: An Introduction (2. baskı)",
    author: "Richard S. Sutton & Andrew G. Barto",
    category: "Uygulama",
    description: "Pekiştirmeli öğrenmenin kurucu ders kitabı · MIT Press · 2018",
    coverImageUrl: "https://covers.openlibrary.org/b/id/8835517-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_031",
    title: "Fundamentals of Data Engineering",
    author: "Joe Reis & Matt Housley",
    category: "Uygulama",
    description: "Veri mühendisliği yaşam döngüsü, modern veri mimarisi referansı · O'Reilly · 2022",
    coverImageUrl: "https://covers.openlibrary.org/b/id/14831765-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_077",
    title: "Machine Learning: A Concise Introduction (2. baskı)",
    author: "Steven W. Knox",
    category: "Uygulama",
    description: "ML temelleri: sınıflandırma, regresyon, kümeleme, boyut indirgeme; Python ve R kod örnekli · Wiley · 2026",
    coverImageUrl: "https://covers.openlibrary.org/b/id/8509194-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_078",
    title: "Machine Learning Theory and Applications",
    author: "Xavier Vasques",
    category: "Uygulama",
    description: "ML matematiği + açık kaynak Python ile uygulama; klasik ve kuantum yaklaşımlar · Wiley · 2024",
    coverImageUrl: "https://media.wiley.com/product_data/coverImage300/18/13942206/1394220618.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_079",
    title: "Metaheuristics for Machine Learning",
    author: "Kalita, Ganesh & Balamurugan",
    category: "Uygulama",
    description: "Doğadan ilham alan optimizasyon; hiperparametre ayarı ve özellik seçimi · Wiley · 2024",
    coverImageUrl: "https://covers.openlibrary.org/b/id/14799354-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_090",
    title: "Yapay Zeka Teknolojisi ve Uygulamaları",
    author: "Ali Şir Attila",
    category: "Uygulama",
    description: "TR'de AI uygulama panoraması.",
    coverImageUrl: "https://www.dikeyeksen.com/cdn/shop/products/yapay_zeka_kitabi_on_kapak_3D_1024x1024.jpg?v=1637574469",
    totalCopies: 2,
  },
  {
    id: "book_xl_091",
    title: "Projelerle Yapay Zeka ve Bilgisayarlı Görü",
    author: "Ümit Aksoylu",
    category: "Uygulama",
    description: "Uygulamalı bilgisayarlı görü projeleri; lab'a birebir.",
    coverImageUrl: "https://www.kodlab.com/2405-thickbox_default/projelerle-yapay-zeka-ve-bilgisayarli-goru.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_094",
    title: "Yapay Zeka İle Programlamanın Mantığı",
    author: "Özel Sebetci",
    category: "Uygulama",
    description: "AI destekli programlama yaklaşımı ve mantığı.",
    coverImageUrl: "https://www.kodlab.com/2578-thickbox_default/yapay-zeka-ile-programlama-mantigi.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_096",
    title: "Yapay Zeka - Kuramdan Uygulamaya",
    author: "Kolektif",
    category: "Uygulama",
    description: "Kuramdan uygulamaya kapsamlı akademik AI kaynağı.",
    coverImageUrl: "https://www.nobelyayin.com/images/urunler/default/nobelyayin_com_19599.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_097",
    title: "Yapay Zeka CNN Algoritması",
    author: "Mehmet Atakan Gündoğdu",
    category: "Uygulama",
    description: "Doğrudan teknik: CNN/derin öğrenme uygulaması.",
    coverImageUrl: "https://i.dr.com.tr/cache/600x600-0/originals/0002129926001-1.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_098",
    title: "Yapay Zeka İle Pratik Uygulamalar",
    author: "Kolektif",
    category: "Uygulama",
    description: "Çeşitli alanlarda pratik AI uygulamaları derlemesi.",
    coverImageUrl: "https://www.kodlab.com/2443-thickbox_default/yapay-zeka-ile-pratik-uygulamalar.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_033",
    title: "Üretken Yapay Zekâ ve Prompt Mühendisliği: 200+ Prompt Örneği",
    author: "Ezgi Avcı (Dr.)",
    category: "LLM & Prompt",
    description: "Türkiye'nin bu alandaki ilk özgün Türkçe kitabı · Seçkin Yayıncılık · 2024",
    coverImageUrl: "https://cdn.seckin.com.tr/getimage/book/664627584_400_wm.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_034",
    title: "AI Engineering: Building Applications with Foundation Models",
    author: "Chip Huyen",
    category: "LLM & Prompt",
    description: "Production-grade LLM/agent mimarisi · O'Reilly · 2025",
    coverImageUrl: "https://covers.openlibrary.org/b/id/15091156-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_035",
    title: "Co-Intelligence: Living and Working with AI",
    author: "Ethan Mollick",
    category: "LLM & Prompt",
    description: "Wharton profesörü, Türkçesi henüz yok · Portfolio · 2024",
    coverImageUrl: "https://covers.openlibrary.org/b/isbn/059371671X-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_036",
    title: "Hands-On Large Language Models",
    author: "Jay Alammar & Maarten Grootendorst",
    category: "LLM & Prompt",
    description: "Görsel ağırlıklı, sezgisel LLM rehberi · O'Reilly · 2024",
    coverImageUrl: "https://covers.openlibrary.org/b/id/15155393-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_037",
    title: "Natural Language Processing with Transformers",
    author: "Lewis Tunstall, Leandro von Werra & Thomas Wolf",
    category: "LLM & Prompt",
    description: "Hugging Face ekibinden transformer tabanlı NLP uygulamaları · O'Reilly · 2022",
    coverImageUrl: "https://covers.openlibrary.org/b/id/14559602-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_038",
    title: "Prompt Engineering for Generative AI",
    author: "James Phoenix & Mike Taylor",
    category: "LLM & Prompt",
    description: "GPT-4 ve difüzyon modelleri için güvenilir prompt teknikleri · O'Reilly · 2024",
    coverImageUrl: "https://covers.openlibrary.org/b/id/15103033-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_039",
    title: "LLM Engineer's Handbook",
    author: "Paul Iusztin & Maxime Labonne",
    category: "LLM & Prompt",
    description: "RAG, fine-tuning, LLMOps — üretim hattı uçtan uca; 2026 listelerinin gözdesi · Packt · 2024",
    coverImageUrl: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1720702048i/216193554.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_040",
    title: "AI Agents in Action",
    author: "Micheal Lanham",
    category: "LLM & Prompt",
    description: "AI ajanları: araç kullanımı, bellek, planlama, çoklu-ajan koordinasyonu · Manning · 2025",
    coverImageUrl: "https://covers.openlibrary.org/b/id/15210869-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_041",
    title: "Building Applications with AI Agents",
    author: "Michael Albada",
    category: "LLM & Prompt",
    description: "Çoklu-ajan sistemlerin tasarımı ve üretimde uygulanması · O'Reilly · 2025",
    coverImageUrl: "https://m.media-amazon.com/images/P/1098176502.01.L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_042",
    title: "Generative AI with LangChain (2. baskı)",
    author: "Ben Auffarth & Leonid Kuligin",
    category: "LLM & Prompt",
    description: "LangChain/LangGraph ile üretici AI ve ajan uygulamaları geliştirme · Packt · 2025",
    coverImageUrl: "https://m.media-amazon.com/images/P/1837022011.01._SCLZZZZZZZ_.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_043",
    title: "RAG-Driven Generative AI",
    author: "Denis Rothman",
    category: "LLM & Prompt",
    description: "RAG mimarileri, vektör veritabanları, kurumsal veriyle LLM entegrasyonu · Packt · 2024",
    coverImageUrl: "https://m.media-amazon.com/images/P/1836200919.01.L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_080",
    title: "Agentic AI For Dummies",
    author: "Pam Baker",
    category: "LLM & Prompt",
    description: "Hedef belirleyip karar veren ajan (agentic) AI sistemlerine giriş; gerçek dünya kullanımları · Wiley · 2025",
    coverImageUrl: "https://m.media-amazon.com/images/P/1394379609.01._SCLZZZZZZZ_.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_081",
    title: "Generative AI For Dummies",
    author: "Pam Baker",
    category: "LLM & Prompt",
    description: "Üretken AI'a giriş; platform seçimi, etkili prompt yazımı, metin/görsel/ses üretimi · Wiley · 2024",
    coverImageUrl: "https://covers.openlibrary.org/b/id/14825190-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_099",
    title: "Üretken Yapay Zeka",
    author: "Jerry Kaplan",
    category: "LLM & Prompt",
    description: "Stanford'lu duayenden Generative AI'ın sağlam özeti.",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:12208740/wh:true/wi:800",
    totalCopies: 2,
  },
  {
    id: "book_xl_100",
    title: "Yapay Zeka İle Sohbetler",
    author: "Ayhan Bozkurt",
    category: "LLM & Prompt",
    description: "LLM sohbet/etkileşim üzerine erişilebilir kaynak.",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:11729724/wi:800/wh:c9341ab0c",
    totalCopies: 2,
  },
  {
    id: "book_xl_101",
    title: "Üretken Yapay Zeka Devrimi",
    author: "Uğur Özker",
    category: "LLM & Prompt",
    description: "GenAI ekosistemine TR kapsamlı bakış.",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:12044656/wi:720",
    totalCopies: 2,
  },
  {
    id: "book_xl_107",
    title: "Python ile Algoritma ve Programlama",
    author: "Kubilay Erkeç",
    category: "Programlama & Temeller",
    description: "Python ile algoritmik düşünme ve programlama pratiği.",
    coverImageUrl: "https://www.kodlab.com/1964-thickbox_default/python-ile-algoritma-ve-programlama.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_108",
    title: "Python İle Veri Yapıları ve Algoritma Analizi",
    author: "Yılmaz Kaya",
    category: "Programlama & Temeller",
    description: "Veri yapıları + algoritma analizi; teknik derinlik.",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:11760949/wh:49b0836af/miw:600/mih:600",
    totalCopies: 2,
  },
  {
    id: "book_xl_109",
    title: "Algoritma",
    author: "Kadir Çamoğlu",
    category: "Programlama & Temeller",
    description: "Dilden bağımsız algoritma temelleri klasiği.",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12228839-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_110",
    title: "Yeni Nesil Tekniklerle JavaScript",
    author: "Uğur Gelişken",
    category: "Programlama & Temeller",
    description: "Modern JS; AI demo/arayüz geliştirme için faydalı.",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:11289687/wh:true",
    totalCopies: 2,
  },
  {
    id: "book_xl_044",
    title: "Yapay Zekâ ve Yeni Dünya Düzeni: Çin–Silikon Vadisi",
    author: "Kai-Fu Lee",
    category: "İş & Strateji",
    description: "Eski adı AI Superpowers · Optimist Yayın Grubu · 2018",
    coverImageUrl: "https://covers.openlibrary.org/b/id/8276795-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_045",
    title: "Geleceğin Endüstrileri",
    author: "Alec Ross",
    category: "İş & Strateji",
    description: "Teknoloji trendleri · Orion Kitabevi · 2017",
    coverImageUrl: "https://m.media-amazon.com/images/P/6055145979.01.L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_046",
    title: "Sıfırdan Bire",
    author: "Peter Thiel & Blake Masters",
    category: "İş & Strateji",
    description: "İnovasyon, girişimcilik klasik · Pegasus Yayınları · 2016",
    coverImageUrl: "https://i.dr.com.tr/cache/500x400-0/originals/0000000696192-1.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_047",
    title: "Yalın Startup",
    author: "Eric Ries",
    category: "İş & Strateji",
    description: "MVP, pivot, deneysel girişimcilik · Maltepe Üniversitesi Kitapları · 2019",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12215222-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_049",
    title: "Sprint: 5 Günde Büyük Sorunları Çözün",
    author: "Jake Knapp, Zeratsky, Kowitz",
    category: "İş & Strateji",
    description: "Google Ventures tasarım sprint · Buzdağı Yayınevi · 2017",
    coverImageUrl: "https://covers.openlibrary.org/b/id/7431269-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_050",
    title: "Yapay Zekâ Devrimi",
    author: "Bernard Marr",
    category: "İş & Strateji",
    description: "AI'nın iş dünyasına etkisi, sektör örnekleri · Kronik Kitap · 2023",
    coverImageUrl: "https://i.dr.com.tr/cache/500x400-0/originals/0001949553001-1.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_051",
    title: "Pazarlama ve Ürün İnovasyonunda Yapay Zeka",
    author: "A. K. Pradeep",
    category: "İş & Strateji",
    description: "Büyük veri + AI + pazarlama · Optimist Kitap · 2020",
    coverImageUrl: "https://i.dr.com.tr/cache/500x400-0/originals/0001890279001-1.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_052",
    title: "Yapay Zeka ve Dijital Pazarlama Aşkı",
    author: "Yasin Kaplan",
    category: "İş & Strateji",
    description: "Türk yazar, dijital reklamda AI uygulamaları · Dijital Pazarlama Okulu · 2024",
    coverImageUrl: "https://i.dr.com.tr/cache/600x600-0/originals/0002139031001-1.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_053",
    title: "Yapay Zekâ Çağında Modern Pazarlama Stratejileri",
    author: "Nurettin Alabay (Dr.)",
    category: "İş & Strateji",
    description: "Türk yazar, AI + pazarlama stratejisi · Akademisyen Yayınları · 2024",
    coverImageUrl: "https://nurettinalabay.com.tr/wp-content/uploads/2025/11/Yapay-Zeka-Caginda-Modern-Pazarlama-Stratejileri-2.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_054",
    title: "Tahmin Eden Makineler: Yapay Zekanın Basit Ekonomisi",
    author: "Ajay Agrawal, Joshua Gans & Avi Goldfarb",
    category: "İş & Strateji",
    description: "AI ekonomisi, ChatGPT öncesi klasik analiz · Buzdağı Yayınevi · 2019",
    coverImageUrl: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1509084205i/36484703.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_055",
    title: "Supremacy: AI, ChatGPT, and the Race That Will Change the World",
    author: "Parmy Olson",
    category: "İş & Strateji",
    description: "FT Yılın İş Kitabı 2024; OpenAI–DeepMind rekabetinin perde arkası · St. Martin's Press · 2024",
    coverImageUrl: "https://covers.openlibrary.org/b/id/14815392-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_056",
    title: "The AI-Savvy Leader",
    author: "David De Cremer",
    category: "İş & Strateji",
    description: "Yöneticiler için AI dönüşümünü yönetme rehberi · HBR Press · 2024",
    coverImageUrl: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1716903591i/182094478.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_082",
    title: "The Vibe Coding Playbook: Building Your Tech Business with AI",
    author: "Siraj Raval",
    category: "İş & Strateji",
    description: "Üretken AI kod asistanlarıyla (Cursor vb.) yazılım/girişim kurma; MVP geliştirme · Wiley · 2026",
    coverImageUrl: "https://covers.openlibrary.org/b/id/15216976-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_083",
    title: "Successful AI Product Creation: A 9-Step Framework",
    author: "Shub Agarwal",
    category: "İş & Strateji",
    description: "AI ürünü geliştirmek için 9 adımlık çerçeve; ürün/uygulama tarafı · Wiley · 2025",
    coverImageUrl: "https://m.media-amazon.com/images/I/71yM-peZUSL._SL1500_.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_084",
    title: "Your AI Roadmap: Actions to Expand Your Career, Money, and Joy",
    author: "Joan Palmiter Bajorek",
    category: "İş & Strateji",
    description: "AI çağında kariyer ve geliri geleceğe hazırlama üzerine pratik tavsiyeler · Wiley · 2025",
    coverImageUrl: "https://m.media-amazon.com/images/P/1394298013.01.L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_118",
    title: "Yapay Zeka Uygulamaları ve Kullanım Alanları - Seçilmiş Ülke Örnekleri",
    author: "Kolektif",
    category: "İş & Strateji",
    description: "Ülke örnekleriyle AI politikaları ve kullanım alanları.",
    coverImageUrl: "https://www.kitapambari.com/u/kitapambari/img/b/y/a/yapay-zeka-uygulamalari-ve-kullanim-alanlari-secilmis-ulke-ornekleriad60efda4991d095ab417bfc7e6a5d0b.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_119",
    title: "Yapay Zeka Şirketi - İş Profesyonelleri İçin Rehber",
    author: "Mehmet Nuri Çankaya",
    category: "İş & Strateji",
    description: "İş profesyonelleri için pratik AI benimseme rehberi.",
    coverImageUrl: "https://cdn.bkmkitap.com/yapay-zeka-sirketi-14025043-95-O.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_120",
    title: "Yöneticiler İçin Yapay Zeka",
    author: "Viktor Dörfler",
    category: "İş & Strateji",
    description: "Yöneticilere yönelik AI karar rehberi (AI for Managers).",
    coverImageUrl: "https://www.iskultur.com.tr/dosyalar/2023/06/yoneticiler-icin-yapay-zeka.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_121",
    title: "Yönetim Biliminde Yapay Zeka",
    author: "Kolektif",
    category: "İş & Strateji",
    description: "Yönetim bilimi ile AI kesişimi; kurumsal karar.",
    coverImageUrl: "https://www.pelikankitabevi.com.tr/u/pelikankitabevi/img/c/u/n/unnamed-1702542898.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_057",
    title: "Süper Zekâ",
    author: "Nick Bostrom",
    category: "Etik & Toplum",
    description: "AI riskleri klasik · Koç Üniversitesi Yayınları · 2014",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12116498-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_059",
    title: "Yaklaşan Dalga",
    author: "Mustafa Suleyman & Michael Bhaskar",
    category: "Etik & Toplum",
    description: "DeepMind/Microsoft AI kurucusu, GenAI çağı · Doğan Kitap · 2024",
    coverImageUrl: "https://covers.openlibrary.org/b/id/15104845-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_061",
    title: "Merhaba Dünya: Makine Çağında İnsan Olmak",
    author: "Hannah Fry",
    category: "Etik & Toplum",
    description: "Algoritmaların adalet/sağlık/suç alanındaki etkisi · HEP Kitap · 2020",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12212110-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_062",
    title: "Yeni Dünya, Yeni Ağ",
    author: "Cem Say",
    category: "Etik & Toplum",
    description: "Türk yazar, internet ve toplum · Bilim ve Gelecek Kitaplığı · 2020",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12121736-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_063",
    title: "Yapay Zeka ve Hukuk",
    author: "Kolektif (Editör: Mustafa Erdem Can)",
    category: "Etik & Toplum",
    description: "Türk hukukçular, AI hukuki boyutu, KVKK · Seçkin Yayıncılık · 2023",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:12071684/wi:800/wh:7840b1dff",
    totalCopies: 2,
  },
  {
    id: "book_xl_064",
    title: "Yapay Zekâ Çağında İnsan Kaynakları",
    author: "Kolektif",
    category: "Etik & Toplum",
    description: "İK profesyonelleri için AI'nın etkileri · Akademisyen Yayınevi · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_065",
    title: "Empire of AI: Dreams and Nightmares in Sam Altman's OpenAI",
    author: "Karen Hao",
    category: "Etik & Toplum",
    description: "OpenAI üzerine araştırmacı gazetecilik; NYT çok satanı, ödül finalisti · Penguin Press · 2025",
    coverImageUrl: "https://covers.openlibrary.org/b/id/15092441-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_122",
    title: "İnsanlık için Yapay Zeka - Kontrol Problemi",
    author: "Stuart Russell",
    category: "Etik & Toplum",
    description: "Human Compatible — AI kontrol problemi; alanın kilit kitabı.",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:11439701/wh:e49c681c2",
    totalCopies: 2,
  },
  {
    id: "book_xl_123",
    title: "Yapay Zeka Güvenliği",
    author: "Şevval Çom",
    category: "Etik & Toplum",
    description: "AI güvenliği/emniyeti; TR'de nadir, güncel konu.",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:12180665/wi:800/wh:b5b1857df",
    totalCopies: 2,
  },
  {
    id: "book_xl_124",
    title: "Yapay Zeka Etiği - Üç Yapay Zeka Kanunu",
    author: "Tamer Yılmaz",
    category: "Etik & Toplum",
    description: "TR özgün AI etiği; Asimov çerçevesinden.",
    coverImageUrl: "https://image01.idefix.com/resize/1200/0/product/19216019/yapay-zeka-etigi-uc-yapay-zeka-kanunu-69736cb46c9d2.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_125",
    title: "Eğitimde Yapay Zeka",
    author: "Kolektif",
    category: "Etik & Toplum",
    description: "Eğitimde AI; kurum içi öğrenme/uygulama perspektifi.",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:11968039/wi:800/wh:64bacb62a",
    totalCopies: 2,
  },
  {
    id: "book_xl_126",
    title: "Yapay Zeka ve Eğitimin Geleceği - Öğretim",
    author: "Priten Shah",
    category: "Etik & Toplum",
    description: "AI çağında öğretim; güncel ve pratik (Wiley).",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:11983157/wi:800/wh:a26949073",
    totalCopies: 2,
  },
  {
    id: "book_xl_127",
    title: "Bilişim Etiği ve Güvenliği",
    author: "Kolektif",
    category: "Etik & Toplum",
    description: "Bilişim etiği + güvenliği; kurumsal farkındalık.",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12109607-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_128",
    title: "Yapay Zeka ve İletişim",
    author: "Sevgi Kavut",
    category: "Etik & Toplum",
    description: "AI'nın iletişim/medya üzerindeki etkisi.",
    coverImageUrl: "https://www.kitaparasi.com/image/data/CIZGI%20KITABEVI/yapay-zeka-ve-iletisim-9786253962272.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_129",
    title: "Sosyal Bilimlerde Yapay Zeka",
    author: "Rıdvan Karabulut",
    category: "Etik & Toplum",
    description: "Sosyal bilimlerde AI yöntem ve etkileri.",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:12129587/wi:800/wh:f782c6607",
    totalCopies: 2,
  },
  {
    id: "book_xl_130",
    title: "Yapay Zeka ve İslam",
    author: "Kolektif",
    category: "Etik & Toplum",
    description: "AI etiğine İslami perspektif; katılım bankası bağlamına özel.",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:11994063/wh:true",
    totalCopies: 2,
  },
  {
    id: "book_xl_131",
    title: "Yapay Zeka - Disiplinlerarası Yaklaşımlar",
    author: "Kolektif",
    category: "Etik & Toplum",
    description: "AI'ya disiplinlerarası akademik bakış.",
    coverImageUrl: "https://www.vbky.com.tr/media/t1/001/709/882/794/yapay-zeka.webp",
    totalCopies: 2,
  },
  {
    id: "book_xl_068",
    title: "İnsanlık 2.0: Tekilliğe Doğru",
    author: "Ray Kurzweil",
    category: "İlham",
    description: "Tekillik klasiği · NTV Yayınları · 2009",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12207607-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_071",
    title: "Architects of Intelligence",
    author: "Martin Ford",
    category: "İlham",
    description: "AI öncüleriyle 23 derinlemesine röportaj · Packt Publishing · 2018",
    coverImageUrl: "https://covers.openlibrary.org/b/id/9351056-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_072",
    title: "Kuantum Üstünlüğü",
    author: "Michio Kaku",
    category: "İlham",
    description: "Kuantum bilgisayar devrimi ve AI'ya etkisi; güncel teknoloji vizyonu · ODTÜ Yayıncılık · 2024",
    coverImageUrl: "https://i.dr.com.tr/cache/500x400-0/originals/0002148146001-1.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_073",
    title: "The Singularity Is Nearer",
    author: "Ray Kurzweil",
    category: "İlham",
    description: "Kurzweil'in 2024'te güncellediği tekillik ve AGI öngörüleri · Viking · 2024",
    coverImageUrl: "https://covers.openlibrary.org/b/id/14861631-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_074",
    title: "Genesis: Artificial Intelligence, Hope, and the Human Spirit",
    author: "Henry Kissinger, Eric Schmidt & Craig Mundie",
    category: "İlham",
    description: "AI çağında insanlık, güç ve gelecek üzerine stratejik bakış · Little, Brown · 2024",
    coverImageUrl: "https://books.google.com/books/content?id=sx36EAAAQBAJ&printsec=frontcover&img=1&zoom=3",
    totalCopies: 2,
  },
  {
    id: "book_xl_075",
    title: "The Worlds I See",
    author: "Fei-Fei Li",
    category: "İlham",
    description: "ImageNet'in yaratıcısından AI tarihine tanıklık eden anı kitabı · Flatiron Books · 2023",
    coverImageUrl: "https://covers.openlibrary.org/b/id/14621790-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_085",
    title: "Generative Knowledge: Think, Learn, Create with AI",
    author: "Paolo Granata",
    category: "İlham",
    description: "AI'ı 'epistemik ortak' olarak ele alan kavramsal kitap; düşünme, öğrenme, yaratma üzerine · Wiley · 2025",
    coverImageUrl: "https://m.media-amazon.com/images/I/81-DAVF6ZPL._SL1500_.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_132a",
    title: "Beyin: Senin Hikayen",
    author: "David Eagleman",
    category: "İlham",
    description: "Beynin kimliğimizi nasıl inşa ettiğine dair nörobilim yolculuğu · Domingo",
    coverImageUrl: "https://covers.openlibrary.org/b/id/10660306-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_132b",
    title: "Incognito – Beynin Gizli Hayatı",
    author: "David Eagleman",
    category: "İlham",
    description: "Bilinçaltının perde arkası: kararlarımızı kim veriyor? · Domingo",
    coverImageUrl: "https://covers.openlibrary.org/b/id/7891426-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_132c",
    title: "Ve... Sonraki Hayattan Kırk Öykü",
    author: "David Eagleman",
    category: "İlham",
    description: "Ölüm sonrasına dair kırk kısa spekülatif öykü · Domingo",
    coverImageUrl: "https://covers.openlibrary.org/b/id/9584588-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_132d",
    title: "Yaratıcı Tür: Fikirler Dünyayı Nasıl Yeniden Yaratıyor?",
    author: "David Eagleman",
    category: "İlham",
    description: "İnsan yaratıcılığının bilişsel kökenleri · Domingo",
    coverImageUrl: "https://covers.openlibrary.org/b/id/13779816-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_133",
    title: "Kuantum Hesaplayıcılar ve Kuantum Hesaplamaya Giriş",
    author: "Mustafa Nuri Ural",
    category: "İlham",
    description: "Kuantum bilişime teknik giriş; ileri görüşlü teknoloji.",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12116514-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_134",
    title: "Tubes - İnternetin Merkezine Yolculuk",
    author: "Andrew Blum",
    category: "İlham",
    description: "İnternetin fiziksel altyapısına gezi; keyifli popüler bilim.",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12131119-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_135",
    title: "Yarının Teknolojik Vizyonu ve Yapay Zeka",
    author: "Kolektif",
    category: "İlham",
    description: "Gelecek teknoloji vizyonu ve AI derlemesi.",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:11795954/wi:720/wh:77f6bdf69",
    totalCopies: 2,
  },
  {
    id: "book_xl_136",
    title: "Yapay Zekanın Kısa Tarihi",
    author: "Michael Wildenhain",
    category: "İlham",
    description: "Kompakt AI tarihçesi; erişilebilir.",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:12009572/wh:true/wi:800",
    totalCopies: 2,
  },
  {
    id: "book_xl_137",
    title: "Yapay Zeka",
    author: "A. Buğra Ferah",
    category: "İlham",
    description: "Genel AI bakışı; TR yazar, erişilebilir anlatım.",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:12152217/wi:800/wh:a9e10d008",
    totalCopies: 2,
  },
  {
    id: "book_xl_138",
    title: "Yapay Zeka 101 - Bir Çırpıda",
    author: "Özgür Taburoğlu",
    category: "İlham",
    description: "Hızlı kavramsal AI girişi.",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:12028129/wh:d6a6756a3/miw:200/mih:200",
    totalCopies: 2,
  },
  {
    id: "book_xl_139",
    title: "Yapay Zeka Okuryazarlığı",
    author: "Kolektif",
    category: "İlham",
    description: "AI okuryazarlığı; kurum geneli farkındalık için değerli.",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:11938551/wi:800/wh:31f19bfa4",
    totalCopies: 2,
  },
  {
    id: "book_xl_140",
    title: "Yapay Zeka Kitabı",
    author: "Anooshirvan Miandji",
    category: "İlham",
    description: "Kapsamlı TR genel AI kitabı.",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:11894734/wh:true/wi:800",
    totalCopies: 2,
  },
  {
    id: "book_xl_141",
    title: "Herkes İçin Yapay Zeka",
    author: "Zafer Demirkol",
    category: "İlham",
    description: "Geniş kitleye yönelik TR AI anlatımı.",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12254040-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_142",
    title: "DK - Kolay Yapay Zeka",
    author: "Kolektif (DK)",
    category: "İlham",
    description: "DK görsel ansiklopedik AI; teknik olmayanlar için ideal (ciltli).",
    coverImageUrl: "https://www.alfakitap.com/media/catalog/product/2/4/246054_9786254499142_80716.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_143",
    title: "Bir Nefeste Yapay Zeka",
    author: "Peter J. Bentley",
    category: "İlham",
    description: "UCL araştırmacısından yoğun-özlü AI girişi.",
    coverImageUrl: "https://cdn.kitapsec.com/image/urun/2025/10/13/1760348037.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_144",
    title: "Yapay Zeka Çağı",
    author: "Byron Reese",
    category: "İlham",
    description: "The Fourth Age — teknoloji-tarih perspektifli pop-AI.",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12199260-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_145",
    title: "Yapay Zeka Felsefesi",
    author: "Kolektif",
    category: "İlham",
    description: "AI felsefesi kapsamlı derleme.",
    coverImageUrl: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1697754740i/125747068.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_146",
    title: "Yapay Zeka Miti",
    author: "Erik J. Larson",
    category: "İlham",
    description: "The Myth of AI — AGI abartısına güçlü eleştiri.",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:11601532/wh:d2ba66e7f/miw:200/mih:200",
    totalCopies: 2,
  },
  {
    id: "book_xl_147",
    title: "Zeka ve Yapay Zeka",
    author: "İlhan Durusoy",
    category: "İlham",
    description: "Zekâ kavramı ile AI'nın karşılaştırmalı incelemesi.",
    coverImageUrl: "https://i.dr.com.tr/cache/600x600-0/originals/0001958118001-1.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_148",
    title: "2062 Yapay Zeka Dünyası",
    author: "Toby Walsh",
    category: "İlham",
    description: "Önde gelen AI profesöründen 2062 gelecek öngörüsü.",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12109539-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_149",
    title: "Yapay Zeka Ne Yapamaz?",
    author: "Ahmet Çevik",
    category: "İlham",
    description: "ODTÜ'lü mantıkçıdan AI'nın sınırları; TR özgün, değerli.",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:12135693/wh:true/wi:800",
    totalCopies: 2,
  },
  {
    id: "book_xl_150",
    title: "Yapay Zeka Neler Yapabilir?",
    author: "Sepp Hochreiter",
    category: "İlham",
    description: "LSTM'in mucidinden; alanın efsanesinden nadir TR çeviri.",
    coverImageUrl: "https://i.dr.com.tr/cache/500x400-0/originals/0002198888001-1.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_151",
    title: "Yapay Zeka: Temel Prensipler",
    author: "Kevin Warwick",
    category: "İlham",
    description: "AI: The Basics — kompakt akademik giriş klasiği.",
    coverImageUrl: "https://www.ginkokitap.com/u/ginkokitap/img/b/y/a/yapay-zeka-1695914723.png",
    totalCopies: 2,
  },
  {
    id: "book_ext_001",
    title: "Sıfırdan Uygulamalara Python Eğitim Kitabı",
    author: "Furkan Değirmenciler",
    category: "Programlama & Temeller",
    description: "Sıfırdan başlayanlar için uygulamalarla Python programlamayı adım adım öğreten eğitim kitabı · Kodlab Yayın · 2024",
    coverImageUrl: "https://www.kodlab.com/2398-thickbox_default/sifirdan-uygulamalarla-python-egitim-kitabi.jpg",
    totalCopies: 2,
  },
  {
    id: "book_ext_002",
    title: "Python Tabanlı Algoritma",
    author: "Kadir Çamoğlu",
    category: "Programlama & Temeller",
    description: "Python ile algoritma mantığını sıfırdan, bol örnekle öğreten uygulamalı bir rehber · Kodlab · 2023",
    coverImageUrl: "https://www.kodlab.com/1943-thickbox_default/python-tabanli-algoritma-.jpg",
    totalCopies: 2,
  },
  {
    id: "book_ext_003",
    title: "Python ile Veri Madenciliği Eğitim Kitabı",
    author: "Caner Erden",
    category: "Uygulama",
    description: "Python ile veri madenciliği tekniklerini uygulamalı örneklerle öğreten Türkçe eğitim kitabı · Kodlab · 2024",
    coverImageUrl: "https://www.kodlab.com/2299-thickbox_default/python-ile-veri-madenciligi.jpg",
    totalCopies: 2,
  },
  {
    id: "book_ext_004",
    title: "Yapay Zeka ile Pratik Uygulamalar",
    author: "Anonim",
    category: "Uygulama",
    description: "Makine öğrenimi, derin öğrenme ve NLP'yi sağlık, finans ve eğitimdeki pratik yapay zeka örnekleriyle anlatan rehber · Kodlab · 2025",
    coverImageUrl: "https://www.kodlab.com/2444-thickbox_default/yapay-zeka-ile-pratik-uygulamalar.jpg",
    totalCopies: 2,
  },
  {
    id: "book_ext_005",
    title: "Python",
    author: "Mustafa Başer",
    category: "Programlama & Temeller",
    description: "Temellerden GUI, web ve SQLite'a uzanan kapsamlı, çok satan Python programlama rehberi · Dikeyeksen",
    coverImageUrl: "https://www.dikeyeksen.com/cdn/shop/files/python_on_kapakv1_grande.jpg?v=1747124552",
    totalCopies: 2,
  },
  {
    id: "book_ext_006",
    title: "Python Eğitim Kitabı",
    author: "Volkan Taşcı",
    category: "Programlama & Temeller",
    description: "Sıfırdan nesne tabanlı programlamaya, bol örnek ve projelerle Python öğreten Türkçe eğitim kitabı · Dikeyeksen Yayıncılık · 2019",
    coverImageUrl: "https://cdn.shopify.com/s/files/1/0158/0204/files/pythonegitimkitabionkapak.jpg?v=1701951173",
    totalCopies: 2,
  },
  {
    id: "book_ext_007",
    title: "Python ile Uçtan Uca Veri Bilimi",
    author: "Engin Bozaba",
    category: "Uygulama",
    description: "Python ile sıfırdan uçtan uca bir veri bilimi projesi geliştirmeyi adım adım öğreten uygulamalı rehber · Dikeyeksen · 2021",
    coverImageUrl: "https://www.dikeyeksen.com/cdn/shop/files/veri_bilimi_kitabi_on_kapakv1_grande.jpg?v=1763542243",
    totalCopies: 2,
  },
  {
    id: "book_ext_008",
    title: "Python ve OpenCV ile Görüntü İşleme",
    author: "Yılmaz Alaca, Emine Yalçın",
    category: "Uygulama",
    description: "Python temellerinden OpenCV ile görüntü işlemeye; yüz ve göz tespiti gibi uygulamalı örnekler sunan rehber · Dikeyeksen Yayıncılık · 2023",
    coverImageUrl: "https://cdn.shopify.com/s/files/1/0158/0204/files/goruntu_isleme_onkapak_v1.jpg?v=1694680289",
    totalCopies: 2,
  },
  {
    id: "book_ext_009",
    title: "Yapay Zekâ Teknolojisi ve Uygulamaları",
    author: "Ali Şir Attila",
    category: "Uygulama",
    description: "Yapay zekâ teknolojisini tüm yönleriyle inceleyen, öne çıkan uygulamaların programlanmasını adım adım gösteren kitap · Dikeyeksen · 2021",
    coverImageUrl: "https://www.dikeyeksen.com/cdn/shop/products/yapay_zeka_on_kapak_v1_grande.jpg?v=1637574470",
    totalCopies: 2,
  },
  {
    id: "book_ext_010",
    title: "React Native in Action",
    author: "Nader Dabit",
    category: "Programlama & Temeller",
    description: "React Native ile iOS ve Android'e yerel mobil uygulamalar geliştirmeyi uygulamalı örneklerle öğreten rehber · Manning Publications · 2019",
    coverImageUrl: "https://images.manning.com/360/480/resize/book/2/8a23d37-c21c-491a-a5a9-498b6b54fe6d/Dabit-React-HI.png",
    totalCopies: 2,
  },
  {
    id: "book_ext_011",
    title: "FastAPI: Modern Python Web Development",
    author: "Bill Lubanovic",
    category: "Programlama & Temeller",
    description: "FastAPI ile modern, hızlı ve tip güvenli Python web API'leri geliştirmeyi uygulamalı biçimde öğreten rehber · O'Reilly Media · 2023",
    coverImageUrl: "https://www.oreilly.com/covers/urn:orm:book:9781098135492/600w/",
    totalCopies: 2,
  },
  {
    id: "book_ext_012",
    title: "Microservice APIs",
    author: "José Haro Peralta",
    category: "Programlama & Temeller",
    description: "Python ile dayanıklı mikroservis API'leri tasarlamayı, REST ve GraphQL desenleriyle uygulamayı öğreten pratik rehber · Manning Publications · 2022",
    coverImageUrl: "https://images.manning.com/360/480/resize/book/2/9295a8c-2948-4af4-8bb3-22613bd437ae/Peralta-HI.png",
    totalCopies: 2,
  },
  {
    id: "book_ext_013",
    title: "Fundamentals of Data Observability",
    author: "Andy Petrella",
    category: "Uygulama",
    description: "Veri sorunlarını erken tespit için veri gözlemlenebilirliği ilkelerini ve uygulamasını anlatan rehber · O'Reilly Media, Inc. · 2023",
    coverImageUrl: "https://learning.oreilly.com/library/cover/9781098133283/",
    totalCopies: 2,
  },
  {
    id: "book_ext_014",
    title: "Data Observability for Data Engineering",
    author: "Michele Pinto, Sammy El Khammal",
    category: "Uygulama",
    description: "Veri hatlarında gözlemlenebilirlik: veri kalitesini izleme ve sorunları erken yakalama rehberi · Packt Publishing · 2023",
    coverImageUrl: "https://static.packt-cdn.com/products/9781804616024/cover/smaller",
    totalCopies: 2,
  },
  {
    id: "book_ext_015",
    title: "Veri Yapıları ve Algoritmalar Bilgisayar Programlama ve Yazılım Mühendisliğinde",
    author: "Dr. Rifat Çölkesen",
    category: "Programlama & Temeller",
    description: "Veri yapıları ve algoritmaları programlama ve yazılım mühendisliği pratiğiyle anlatan kapsamlı ders kitabı · Papatya Bilim · 2022",
    coverImageUrl: "https://img.kitapyurdu.com/v1/getImage/fn:8640249/wi:800/wh:9765a29f6",
    totalCopies: 2,
  },
  {
    id: "book_ext_016",
    title: "The Master Algorithm: How the Quest for the Ultimate Learning Machine Will Remake Our World",
    author: "Pedro Domingos",
    category: "İlham",
    description: "Makine öğrenmesinin beş ekolünü ve her şeyi öğrenen nihai algoritma arayışını anlatan popüler bilim kitabı · Penguin Books · 2017",
    coverImageUrl: "https://covers.openlibrary.org/b/id/9321915-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_ext_017",
    title: "Veri Bilim",
    author: "Necmi Gürsakal",
    category: "Giriş",
    description: "Veri biliminin temel kavramlarını, büyük veri ve analitik yaklaşımları Türkçe tanıtan kapsamlı bir kaynak · Dora Yayıncılık · 2019",
    coverImageUrl: "https://m.media-amazon.com/images/I/61nQSng4yXL._SL1000_.jpg",
    totalCopies: 2,
  },
  {
    id: "book_ext_018",
    title: "Veri Bilimi",
    author: "Çiğdem Aytekin, Cem S. Sütcü",
    category: "Giriş",
    description: "Veri bilimi kavramlarını, yöntemlerini ve uygulama alanlarını Türkçe tanıtan giriş kitabı · Paloma Yayınevi · 2019",
    coverImageUrl: "https://m.media-amazon.com/images/I/51m-Ng7khiL._SL1257_.jpg",
    totalCopies: 2,
  },
  {
    id: "book_ext_019",
    title: "Veri Bilimi İçin Python: Çözümlü Örnekler ve Uygulamalı Gösterimleriyle",
    author: "Burak Özkan",
    category: "Uygulama",
    description: "Python ile veri bilimini çözümlü örnekler ve uygulamalı gösterimlerle öğreten Türkçe kaynak · Papatya Bilim · 2022",
    coverImageUrl: "https://m.media-amazon.com/images/I/41-DgLnVJJL.jpg",
    totalCopies: 2,
  },
  {
    id: "book_ext_020",
    title: "Veri Dedektifi - Sayıların Gizlediklerini Anlamanın 10 Kuralı",
    author: "Tim Harford",
    category: "İlham",
    description: "İstatistiklere eleştirel bakmayı ve sayıların ardındaki gerçeği görmeyi öğreten 10 pratik kural · Pegasus Yayınları · 2025",
    coverImageUrl: "https://m.media-amazon.com/images/I/51Ev09+CrCL.jpg",
    totalCopies: 2,
  },
  {
    id: "book_ext_021",
    title: "The AI-First Company: How to Compete and Win with Artificial Intelligence",
    author: "Ash Fontana",
    category: "İş & Strateji",
    description: "Yapay zekâyı işin merkezine koyarak rekabette öne geçmek isteyen şirketler için pratik strateji rehberi · Portfolio · 2021",
    coverImageUrl: "https://m.media-amazon.com/images/I/71thkkqxyIL._SL500_.jpg",
    totalCopies: 2,
  },
  {
    id: "book_ext_022",
    title: "İnternet for Dummies",
    author: "John R. Levine, Margaret Levine Young",
    category: "Giriş",
    description: "İnternete bağlanma, e-posta, sosyal medya ve çevrimiçi güvenliği yeni başlayanlara anlatan pratik rehber · Nobel Yaşam (For Dummies Türkiye) · 2017",
    coverImageUrl: "https://www.dummiestr.com/img/urunler/397674.jpg",
    totalCopies: 2,
  },
  {
    id: "book_ext_023",
    title: "Data Structures and Algorithms",
    author: "Alfred V. Aho, John E. Hopcroft, Jeffrey D. Ullman",
    category: "Programlama & Temeller",
    description: "Aho, Hopcroft ve Ullman'dan veri yapıları ile algoritmaların temellerini işleyen klasik ders kitabı · Addison-Wesley · 1983",
    coverImageUrl: "https://covers.openlibrary.org/b/isbn/0201000237-L.jpg",
    totalCopies: 2,
  },
];
